#pragma once
#define WIFI_SSID "MyWifi"
#define WIFI_PASS "mySuperPuperParol"
#define BOT_TOKEN "0123456789:BOTShowERToNKen_CLI"
#define ADMIN_ID "1433760480"

// Душ 1
#define SHOWER_1_TIMER_DIO 1
#define SHOWER_1_TIMER_CLK 2
#define SHOWER_1_BUTTON 3
#define SHOWER_1_TEMPERATURE_BUTTON_1 4
#define SHOWER_1_TEMPERATURE_BUTTON_2 5
#define SHOWER_1_TEMPERATURE_BUTTON_3 6
#define SHOWER_1_TEMPERATURE_BUTTON_4 7

// Душ 2
#define SHOWER_2_TIMER_DIO 8
#define SHOWER_2_TIMER_CLK 9
#define SHOWER_2_BUTTON 10
#define SHOWER_2_TEMPERATURE_BUTTON_1 11
#define SHOWER_2_TEMPERATURE_BUTTON_2 12
#define SHOWER_2_TEMPERATURE_BUTTON_3 13
#define SHOWER_2_TEMPERATURE_BUTTON_4 14